server_name: nats-site-a
cluster: {
  name: site-a
  listen: 0.0.0.0:6222
  routes: [
    nats://nats-site-a:6222
  ]
}
gateway: {
  name: site-a
  port: 7222
  gateways: [
    { name: site-b, url: nats://nats-site-b:7222 }
  ]
}
jetstream: {
  domain: site-a
  store_dir: /data/jetstream
}
