server_name: nats-site-b
cluster: {
  name: site-b
  listen: 0.0.0.0:6222
  routes: [
    nats://nats-site-b:6222
  ]
}
gateway: {
  name: site-b
  port: 7222
  gateways: [
    { name: site-a, url: nats://nats-site-a:7222 }
  ]
}
jetstream: {
  domain: site-b
  store_dir: /data/jetstream
}
