// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDirectoryStore is a mock of DirectoryStore interface.
type MockDirectoryStore struct {
	ctrl     *gomock.Controller
	recorder *MockDirectoryStoreMockRecorder
	isgomock struct{}
}

// MockDirectoryStoreMockRecorder is the mock recorder for MockDirectoryStore.
type MockDirectoryStoreMockRecorder struct {
	mock *MockDirectoryStore
}

// NewMockDirectoryStore creates a new mock instance.
func NewMockDirectoryStore(ctrl *gomock.Controller) *MockDirectoryStore {
	mock := &MockDirectoryStore{ctrl: ctrl}
	mock.recorder = &MockDirectoryStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirectoryStore) EXPECT() *MockDirectoryStoreMockRecorder {
	return m.recorder
}

// EnsureIndexes mocks base method.
func (m *MockDirectoryStore) EnsureIndexes(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureIndexes", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureIndexes indicates an expected call of EnsureIndexes.
func (mr *MockDirectoryStoreMockRecorder) EnsureIndexes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureIndexes", reflect.TypeOf((*MockDirectoryStore)(nil).EnsureIndexes), ctx)
}

// FindSiteByID mocks base method.
func (m *MockDirectoryStore) FindSiteByID(ctx context.Context, siteID string) (*site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSiteByID", ctx, siteID)
	ret0, _ := ret[0].(*site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSiteByID indicates an expected call of FindSiteByID.
func (mr *MockDirectoryStoreMockRecorder) FindSiteByID(ctx, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSiteByID", reflect.TypeOf((*MockDirectoryStore)(nil).FindSiteByID), ctx, siteID)
}

// FindUserByAccount mocks base method.
func (m *MockDirectoryStore) FindUserByAccount(ctx context.Context, account string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByAccount", ctx, account)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByAccount indicates an expected call of FindUserByAccount.
func (mr *MockDirectoryStoreMockRecorder) FindUserByAccount(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByAccount", reflect.TypeOf((*MockDirectoryStore)(nil).FindUserByAccount), ctx, account)
}
